apiVersion: cluster.x-k8s.io/v1beta2
kind: ClusterClass
metadata:
  name: ${CLUSTER_CLASS_NAME}
spec:
  controlPlane:
    templateRef:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta2
      kind: AWSManagedControlPlaneTemplate
      name: "${CLUSTER_CLASS_NAME}-control-plane"
  infrastructure:
    templateRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSManagedClusterTemplate
      name: "${CLUSTER_CLASS_NAME}"
  workers:
    machineDeployments:
      - class: default-worker
        bootstrap:
          templateRef:
            name: "${CLUSTER_CLASS_NAME}-md-bootstraptemplate"
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
            kind: EKSConfigTemplate
        infrastructure:
          templateRef:
            name: "${CLUSTER_CLASS_NAME}-md-bootstraptemplate"
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
            kind: AWSMachineTemplate
---
kind: AWSManagedClusterTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
metadata:
  name: "${CLUSTER_CLASS_NAME}"
spec:
  template:
    spec: {}
---
kind: AWSManagedControlPlaneTemplate
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
metadata:
  name: "${CLUSTER_CLASS_NAME}-control-plane"
spec:
  template:
    spec:
      region: "${AWS_REGION}"
      sshKeyName: "${AWS_SSH_KEY_NAME}"
      version: "${KUBERNETES_VERSION}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: "${CLUSTER_CLASS_NAME}-md-bootstraptemplate"
spec:
  template:
    spec:
      instanceType: "${AWS_NODE_MACHINE_TYPE}"
      iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
      sshKeyName: "${AWS_SSH_KEY_NAME}"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: EKSConfigTemplate
metadata:
  name: "${CLUSTER_CLASS_NAME}-md-bootstraptemplate"
spec:
  template: {}
