#INFO: This manifest create a bring-your-own-AWS-infrastructure cluster where we can reuse the existing AWS resources while creating AWS Clusters which gives flexibility bring our own existing resources into the cluster instead of creating new resources again
#REF: https://cluster-api-aws.sigs.k8s.io/topics/bring-your-own-aws-infrastructure

apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  labels:
    cni: calico
    ccm: external
    csi: external
  name: h10h-byoai-cluster #NOTE: change the cluster name based on your preference
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16 #WARN: Must not overlap with the VPC CIDR block
  topology:
    classRef:
      name: aws-quick-start
    controlPlane:
      replicas: 1
    variables:
      - name: region
        value: us-west-2
      - name: vpc
        value:
          id: vpc-010deb11e3a12cd03 #NOTE: replace with your existing VPC ID
      - name: subnets
        value:
          #NOTE: replace with your existing subnet IDs
          - id: "subnet-0e201f70ee2a1084b"
          - id: "subnet-0139794a6b43308a7"
      - name: securityGroupOverrides
        value:
          #NOTE: replace with your existing SG IDs
          control-plane: sg-01d128b4b1d4965dd
          node: sg-0fad75ce7b081f3b7
          lb: sg-0a5f4528e4a1203b7
      - name: controlPlaneLoadBalancer
        value:
          loadBalancerType: nlb
          scheme: internet-facing
          healthCheckProtocol: TCP
          name: h10h-byoai-apiserver-lb
        #WARN: Remember to create key pair first
      - name: sshKeyName
        value: capa-rsa-key-pair #NOTE: change the key pair name based on your preference
      - name: controlPlaneMachineType
        value: t3.medium
      - name: workerMachineType
        value: t3.medium
      - name: rootVolume
        value:
          size: 40 # GiB
          type: gp3 # gp3, gp2, io1, io2, standard
      - name: amiID
        # Command to find AMI: clusterawsadm ami list --os=ubuntu-22.04 --region=us-west-2
        # Ref: https://cluster-api-aws.sigs.k8s.io/clusterawsadm/clusterawsadm_ami_list
        value: ami-0f6c1e86cf27c3693 #NOTE: AMI for ubuntu 22.04 - k8s v1.32 - us-west-2 region
    version: v1.32.0
    workers:
      machineDeployments:
        - class: default-worker
          name: worker-node
          replicas: 2
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: crs-cni
spec:
  clusterSelector:
    matchLabels:
      cni: calico
  resources:
    - kind: ConfigMap
      name: cni-calico
  strategy: ApplyOnce
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: crs-ccm
spec:
  clusterSelector:
    matchLabels:
      ccm: external
  resources:
    - kind: ConfigMap
      name: aws-ccm-addon
  strategy: ApplyOnce
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: crs-csi
spec:
  clusterSelector:
    matchLabels:
      csi: external
  resources:
    - kind: ConfigMap
      name: aws-ebs-csi-driver-addon
  strategy: ApplyOnce
