apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  labels:
    cni: calico
    ccm: external
    csi: external
  name: h10h-aws-cluster #NOTE: change the cluster name based on your preference
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16 #WARN: Must not overlap with the VPC CIDR block
  topology:
    classRef:
      name: aws-quick-start
    controlPlane:
      replicas: 1
    variables:
      - name: region
        value: us-west-2
      - name: vpc
        value:
          cidrBlock: "192.168.0.0/16" #WARN: Must not overlap with the pods CIDR block
          availabilityZoneUsageLimit: 1
      - name: subnets
        value:
          - id: "subnet-public-h10h"
            cidrBlock: "192.168.0.0/20"
            availabilityZone: "us-west-2a"
            isPublic: true
          - id: "subnet-private-h10h"
            cidrBlock: "192.168.16.0/20"
            availabilityZone: "us-west-2a"
            isPublic: false
        #WARN: Remember to create key pair first
      - name: controlPlaneLoadBalancer
        value:
          loadBalancerType: nlb
          scheme: internet-facing
          healthCheckProtocol: TCP
      - name: sshKeyName
        value: capa-rsa-key-pair #NOTE: change the key pair name based on your preference
      - name: controlPlaneMachineType
        value: t3.medium
      - name: workerMachineType
        value: t3.medium
      - name: rootVolume
        value:
          size: 40 # GiB
          type: gp3 # gp3, gp2, io1, io2, standard
      - name: amiID
        # Command to find AMI: clusterawsadm ami list --os=ubuntu-22.04 --region=us-west-2
        # Ref: https://cluster-api-aws.sigs.k8s.io/clusterawsadm/clusterawsadm_ami_list
        value: ami-0f6c1e86cf27c3693 #NOTE: AMI for ubuntu 22.04 - k8s v1.32 - us-west-2 region
    version: v1.32.0
    workers:
      machineDeployments:
        - class: default-worker
          name: worker-node
          replicas: 2
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: crs-cni
spec:
  clusterSelector:
    matchLabels:
      cni: calico
  resources:
    - kind: ConfigMap
      name: cni-calico
  strategy: ApplyOnce
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: crs-ccm
spec:
  clusterSelector:
    matchLabels:
      ccm: external
  resources:
    - kind: ConfigMap
      name: aws-ccm-addon
  strategy: ApplyOnce
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: crs-csi
spec:
  clusterSelector:
    matchLabels:
      csi: external
  resources:
    - kind: ConfigMap
      name: aws-ebs-csi-driver-addon
  strategy: ApplyOnce
