apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  labels:
    cni: calico
    ccm: external
    csi: external
  name: h10h-aws-cluster #NOTE: change the cluster name based on your preference
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16 #WARN: Must not overlap with the VPC CIDR block
  topology:
    classRef:
      name: aws-quick-start
    controlPlane:
      replicas: 1
    variables:
      - name: region
        value: us-east-1
      - name: vpc
        value:
          cidrBlock: "192.168.0.0/16" #WARN: Must not overlap with the pods CIDR block
          availabilityZoneUsageLimit: 1
      - name: subnets
        value:
          - id: "subnet-public-h10h"
            cidrBlock: "192.168.0.0/20"
            availabilityZone: "us-east-1a"
            isPublic: true
          - id: "subnet-private-h10h"
            cidrBlock: "192.168.16.0/20"
            availabilityZone: "us-east-1a"
            isPublic: false
        #WARN: Remember to create key pair first
      - name: sshKeyName
        value: capa-rsa-key-pair #NOTE: change the key pair name based on your preference
      - name: controlPlaneMachineType
        value: t3.medium
      - name: workerMachineType
        value: t3.medium
      - name: amiID
        value: ami-06f8fe92d4b567082 #NOTE: AMI for ubuntu 22.04 - k8s v1.32
    version: v1.32.0
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: 1
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: crs-cni
spec:
  clusterSelector:
    matchLabels:
      cni: calico
  resources:
    - kind: ConfigMap
      name: cni-calico
  strategy: ApplyOnce
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: crs-ccm
spec:
  clusterSelector:
    matchLabels:
      ccm: external
  resources:
    - kind: ConfigMap
      name: aws-ccm-addon
  strategy: ApplyOnce
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: crs-csi
spec:
  clusterSelector:
    matchLabels:
      csi: external
  resources:
    - kind: ConfigMap
      name: aws-ebs-csi-driver-addon
  strategy: ApplyOnce
