---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capa-byoai
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/High10Hunter/cloud-agnostic.git
    path: gitops/manifests/clusters/capa-byoai
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default # reuse the configmap of the self-hosted cluster
  syncPolicy:
    automated:
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
